sudo: required
services:
- docker
language: nix
deploy:
  provider: script
  script: make dockerize && make docker-push VERSION="$TRAVIS_BRANCH"
  on:
    repo: GregBowyer/marge-bot
    all_branches: true
    condition: "$TRAVIS_BRANCH = $(cat version) || $TRAVIS_BRANCH = master"
env:
  global:
  - secure: KAA1ed9PATGs0h0uYwTK4LaZ9YXxFchaZJoXP5rctBOVSI17SvWd0HQ0AqXRH0/vSl8GiulGq6w0/CdS8MrTcZakvNRUmlIfdgRsHP+vbmtCbKaqYmzujnxqLNZx2QProARPg6oas7Ayr5gHoAaWK0fC8LDl16zbLamDU2ePKAX1vsBvI7tYAMLfThO1JYeccMag8US8UxM2bpT8ONgbgXOTX5aD6TbpnTq4TYyWgkaqiVgkeHyqoJaCJ0uixiIOoz9A+EHHGrHXSyhQHnAVe5ASGOyxqmdPwDjxCSMr8DPZi4gi4HePlTBZIA/CdqiNZirRLbh3uGUH949vAPeOmdrNmHeRQvR6cOV2oBbnzL2c421b+YmcrfWhurUUzs4YU1cmmxRvZfWTTM1if19urVWqsYGNR75Wt4e+Nz+2FqbJ0RrWLfBXvL4VgnHV2cwNhwXIDTPsTuXWfc85v5k4QTmOujNkFP8KaTw0a/xofqv/1nwnMdo+OF+cnnkjicQIWF7MfxXNA0L8meGNzBQhrYO2VM31wkBuwq+D2lFjdtPJDRb6ZhGSembpsdhMn36PxYXvUNdEK2FZHeRthw4ChN5051vqlp/RzrexVwLPNrh+oB3Dqi+MZE4LGJcqAfSz0Xrw2AtoI6W4bXl0zYj1eLHi3+Xy9+02hnRIdjAaDxI=
  - secure: kLCbjPM9xy9SC/f2A1ebCTCKk2FKXW4fpX83sv2Nw9govmS4oIf5y8IiGQxBR4NhctZqzjYQYCwnT8YxLOGv7nGK8q6CQ11GXy505EIPkj+Dxir9ZQDAT/dP07VVfeB3iyX/y/3jVmlUAB6fx6Ue8hGCFDE5OXXCF+qxs/OT+msDiqWiFW98Fg4g4g5TOIkpk3K5Vf9DFbnzz8JXYhco6He3dNBCntXmmXuQdwIllA8phNLEM9rhmSKgD8Cvq2GBsWHwC7MjNgkKuKywAYXqHbAKl8RXHOrGOaIoSs1LkDnUozFLZzUmx/J7amjp8q1DzTd2Uaa3AgXvQzlyolMXHBiIazVeivr6lDOwrv+McSO1/slbXtjXYkqgKNjHB4h8hfxroiJKgPU7tOVOb/UKRsQbjz1PA7I6JjUVKnQxhO9Xhq0ktXp0CKsegrPxHqrNPA66kYaqP679CC0T4Kfa7n3NRxEXM0DYg7z98NNT8dbpBrQFwgH4dSvrjvGxgqpv/+zPtazSoy1jhP4mt/H5ku3xJvats8gzUBLI01CHF81YHM2ff4Gz2+xtUh9xRYjGfQGkunhHP7DJX9CRmjKATtRz8nSstGxmoT8zeNXv/H+HARqtEil7idzXOjkito7NOsRLgLnhUH5kM6tgJEgh4B9sKClN6EjpGv7/soa/XIE=
