sudo: required
services:
- docker
language: nix
deploy:
  provider: script
  script: make dockerize && make docker-push VERSION="$TRAVIS_BRANCH"
  on:
    repo: GregBowyer/marge-bot
    all_branches: true
    condition: "$TRAVIS_BRANCH = $(cat version) || $TRAVIS_BRANCH = master"
env:
  global:
  - secure: Pyrln53t/bJcXI5wFIvrlPZZOuOBB9ikNwqPZiUAznYz+5yoTFwoHoPA4gvfxNEb8MBB5NHQ5Ki8pGBtfzVjJ5hskmR9q0jBIcdY7YVNeGLiRDPXWZjuc6Wo6KRGaF38VdS7AGpBlbP6kge48m+bB8esTQ2CC0HBjGXoozujomajP9oY3hhdrbGXlDxJmbFVqCf9d54A4xPntInGsrjMpexUSTui5TaZYr5CUojqGpIftLoMxOU9oJ+IuEJvNvg14yWqDk+P7DlyaeN2673HMjc0hz2T92ZIKyANSiGi8TIVnOuLvWvLs2nxuODmTqTaMGJ3dcMpcZIS+6vRt+dWYLcEyxsgZna5oPQ8VrLcOpc5Xp/oDYdc/SF2YZPeTIr54SGLoojoCAsQttTXal1SfJ9h9Oklhi/+bT7CfEZJSqrkymrpdLzWT3Hx9FzMhLd0/PXVn5ebJd5iGFzDX0GUmS7c6S/bRLkoWnZOU4mWfveTlp3kmMWlMrdLGWu1eOecEXiQdXron9OPhEocw9DTfxqNmOXnq+leAr3jiqn3TxiLRCSpEFju9dENdo7OwuyIy50inlmaCWol+CXfHbbpZzfc/s14u6DKIJlf/j05sf3vnU7fnL+G5+KNNHpO8MJMBN0b/gzUB1l+NnIbsymWTIOoKHMOYQh9ATB6iru1k5c=
  - secure: Ojp4I1IX+G6vldyr5/t9XR6eEwHsfXI6fh40UirqheYYbk/WXUcIr/y0xt0YkCb4tncuxa63RpUPdRXuFz8bSplKZI0XKhHVv5lceXTDJ8gz5X230qgsMI1Rw7kK8BjtwPWBzgRGX24pHQWnBZMq+AVBESu1VPTdqs9ev6KN02Yr8V5BAQ+rqXY689f4x+riVo7dO8hpa6RVotp2LoyCczwVj0ZmEo+wrVv4OhspweQUZDGra0kqQsRyb+BfkcVb35uxhDyfFbgt/jBT2G+aHgpC8HMgngXEfgsEHCoOQ2pt6VbMCbINtMgvIDM0cjlxJh2VzFQQyUraF8z2jGgKI15Cd0AbM3tJ9ZdilpJkENLR63FlNIT88X7Kzw+wJM/jyqq00P4Dix7d61QF9OKpj/L6w9So5TNbgYxdhv9n8sfHggh0u09dmmMaOPa0OKMiNE72qOrDOFHGcRYvler5j2WUghFNzCV1PYI3xOQqGvyRyywqrC8SmcFl3WXzkC36LN54PDxs39VA4TA5OM6hnvHGiUOp7LzI2mGDXw9pomzpsxmyEQArZsZSfKmO/ScbeYUUTNOCozvlG5AwnrVW7ixsW4g/LjY6HP9ntgYd3CauzEvolQKtxbVY4DLNsuYf0Nd67f1VI474jTEw1v8/GTcPHfuxjicTQ1Q8vqjGjhg=
